CREATE TABLE anime (
    id integer PRIMARY KEY,
    type_id integer,
    rating_id integer,
    season_id integer,
    source_id integer NOT NULL,
    status_id integer NOT NULL,
    title varchar(512) NOT NULL,
    title_japanese varchar(512) NOT NULL,
    url text NOT NULL,
    image_url text NOT NULL,
    score double precision NOT NULL,
    scored_by double precision,
    start_date date,
    end_date date,
    synopsis varchar(5000),
    rank double precision,
    popularity integer NOT NULL,
    members integer NOT NULL,
    favorites integer NOT NULL,
    episodes double precision,
    year double precision,
    watching integer NOT NULL,
    completed integer NOT NULL,
    on_hold integer NOT NULL,
    dropped integer NOT NULL,
    plan_to_watch integer NOT NULL,
    total integer NOT NULL,
    score_1_votes double precision NOT NULL,
    score_1_percentage double precision NOT NULL,
    score_2_votes double precision NOT NULL,
    score_2_percentage double precision NOT NULL,
    score_3_votes double precision NOT NULL,
    score_3_percentage double precision NOT NULL,
    score_4_votes double precision NOT NULL,
    score_4_percentage double precision NOT NULL,
    score_5_votes double precision NOT NULL,
    score_5_percentage double precision NOT NULL,
    score_6_votes double precision NOT NULL,
    score_6_percentage double precision NOT NULL,
    score_7_votes double precision NOT NULL,
    score_7_percentage double precision NOT NULL,
    score_8_votes double precision NOT NULL,
    score_8_percentage double precision NOT NULL,
    score_9_votes double precision NOT NULL,
    score_9_percentage double precision NOT NULL,
    score_10_votes double precision NOT NULL,
    score_10_percentage double precision NOT NULL,
    CONSTRAINT fk_anime_type FOREIGN KEY (type_id) REFERENCES type (id),
    CONSTRAINT fk_anime_rating FOREIGN KEY (rating_id) REFERENCES rating (id),
    CONSTRAINT fk_anime_season FOREIGN KEY (season_id) REFERENCES season (id),
    CONSTRAINT fk_anime_source FOREIGN KEY (source_id) REFERENCES source (id),
    CONSTRAINT fk_anime_status FOREIGN KEY (status_id) REFERENCES status (id)
);